### ISSUE TITLE
CAP Operator

### ISSUE THREAD

**Issue by drpaneas** [SUSE/skuba#1019]
# EPIC

Since Cloud Foundry gets installed on top of CaaSP, the best way to install it, it would be using an [operator](https://kubernetes.io/docs/concepts/extend-kubernetes/operator/).

### CAP installation controller
As a customer of CAP and CaaSP, I want to install and update CAP using an operator. For example:

```
1. kubectl create -f cloudfoundry_crd.yaml
2. kubectl -n cloud-foundry create -f cloudfoundry_cr.yaml
```

An operator will be deployed onto the CaaSP cluster and install CAP. This controller can be written by the CaaSP team.

### CAP update controller

As a customer of CAP and CaaSP, I want to update CAP using an operator. For example:

```
1. kubectl -n cloud-foundry edit cloud-foundry-cluster # or kubectl patch
2. Change the version from X to Y
3. Update the object by saving the changes
```

The operator will reconcile and update CAP for you. This controller can be written by the CAP team.

### How to do it

* Create a new repository in Github and setup the CI system for Go projects.
* Create a CRD `cloudfoundry_crd.yaml` that defines what CAP means for CaaSP.
* Create an example `cloudfoundry_cr.yaml` with the appropriate values for CAP installation.
* Document the fields and the values the customer can select.
* Write an operator either [kubebuilder](https://book.kubebuilder.io/) or [operators-sdk](https://github.com/operator-framework/operator-sdk) 
* Write individual controllers for this operator (e.g. one controller for installation, and one for updates)
* Developers submit PR including unit-tests written in Ginkgo to make yourself familiar with kubernetes upstream. If you have dependencies, mock them (e.g. `gomock`).

If there is an error that can be fixed automatically the controller will reconcile either immediately or after a couple of seconds (you can specify it). If the error cannot be fixed by the controller, it will stop reconciling.

**Comment by evrardjp** [comment]
I don't see the need for an operator and controller to install CAP. I do see one for updating it though.
Why do you need an operator to install CAP? What problem does it solve?

Note: There are other tools to build operator if necessary, though those two are popular.

**Comment by drpaneas** [comment]
Using operators for installing/managing software on top of Kubernetes is the de-facto best practice for production kubernetes deployments. If you provide enterprise software that gets installed on-top of CaaSP, such us (Prometheus, Elastic, whatever) without using operators, you have to have really really good documentation and hope the customers are following it to the point. The proposal is about having a CAP operator. What controllers this operator will have it's up to you and your customer needs. Usually, all controllers start with the installation, hence I proposed it.

**Comment by flavio** [comment]
This is already being worked by SUSE, IBM, SAP and others with the [cf-operator](https://github.com/cloudfoundry-incubator/cf-operator). More [here](https://www.cloudfoundry.org/blog/kubecf-now-an-incubating-project-of-cloud-foundry-foundation/)

**Comment by evrardjp** [comment]
Awesome, thanks @flavio . I sure hope it's not only installing :)
