### ISSUE TITLE
Aggregator issue for 4.2.0 updates

### ISSUE THREAD

**Issue by dannysauer** [SUSE/skuba#1021]
Opening an issue to collect together the PRs which still need included in the 4.2.0 release version.  There might be a better way to do this, but when did that stop anyone? :D

**Comment by evrardjp** [comment]
Shouldn't this be an epic instead? ;)

**Comment by dannysauer** [comment]
It should probably be a milestone, but I couldn't find the "new milestone" place until well after I made this. 😂

Next time...
