### ISSUE TITLE
Ensure that config files are placed atomically

### ISSUE THREAD

**Issue by dannysauer** [SUSE/skuba#103]
Per the discussion linked below, "someone" should verify that the file copy process is performing atomic copies.  Namely, that it's creating a $tempname on the destination (in the same directory as $realname, so the filesystem is the same and the actual rename syscall can be used), populating the contents to that temp name, and then renaming $tempname to $realname.

_Originally posted by @dannysauer in https://github.com/SUSE/caaspctl/pull/98/review_comment/create_
(renamed to https://github.com/SUSE/skuba/pull/98)

**Comment by evrardjp** [comment]
Does this still apply? I am looking to cleanup all the cruft in issues :)

**Comment by dannysauer** [comment]
Following up.  One of us will either close or do some research.

**Comment by dannysauer** [comment]
This is still technically "a thing", but somewhat insignificant given future direction.  Closing.
