### ISSUE TITLE
Validate persistent system config files after writing

### ISSUE THREAD

**Issue by dannysauer** [SUSE/skuba#104]
Regarding the files caaspctl puts in modprobe.d and sysctl.d, there should be validation that these files work as expected on the system.  If we only put the files in place and do not validate them, then it's possible that they won't load as expected on the next reboot.  Depending on when the next reboot happens, this could be far enough in to the future that the cluster admin won't remember to check.

_Excerpt from post by @dannysauer in https://github.com/SUSE/caaspctl/pull/98 :_
> 
> If a file doesn't end in .conf, it doesn't get loaded on boot, so a reboot still brings you back to the old settings.
> 
> The main benefit to applying the file is that the file is tested, so it'll definitely work on reboot.  As-is, nothing tests that the file contents will do what's expected until the next reboot.  Based on the code, there's no reason that the file wouldn't work - except for the (hopefully) unlikely situation where the file is created with incomplete contents.  Maybe caaspctl is interrupted, or the network fails, or etc.  I haven't looked at the file copy code, but hopefully it already writes to a temporary file in the same directory and then renames to the final name, preventing that situation?  If not, then it should. Any config file edit should be fully atomic; any possibility of generating a partial config file should be avoided.

**Comment by evrardjp** [comment]
Does that still apply? Is it properly prioritized?

**Comment by ereslibre** [comment]
While this is certainly desirable, I think we can close this given the current state of the project.
