### ISSUE TITLE
Enrich skuba list nodes with machine_id and internal_ips

### ISSUE THREAD

**Issue by mbologna** [SUSE/skuba#1122]
As part of the SUSE Manager integration, we are relying on python-kubernetes to enrich the output from skuba to gather 'machine-id' and 'internal-ips' for every node of the cluster.

Would it be possible to enrich the output of `skuba` list nodes to return this data as well?

Here is how we are doing it:

https://github.com/uyuni-project/uyuni/pull/2226/commits/3168a7ebe0b5b6742415fac111615cd78403d5f2#diff-c6e44956fb03d01218c80e7bd924ed50R109-R123

https://github.com/uyuni-project/uyuni/pull/2226/commits/3168a7ebe0b5b6742415fac111615cd78403d5f2#diff-c6e44956fb03d01218c80e7bd924ed50R109-R123

**Comment by evrardjp** [comment]
While I am not against the idea, what's the reason? 

I am not sure I understand why machine-id would be necessary, and where do you need it. Could you clarify?

**Comment by mbologna** [comment]
> While I am not against the idea, what's the reason?
> 
> I am not sure I understand why machine-id would be necessary, and where do you need it. Could you clarify?

We are using the output of `skuba cluster status` inside SUSE Manager/Uyuni to match the nodes that are part of the cluster with the nodes known/registered to SUSE Manager/Uyuni.
You can have a look at the two commits pointed above to see how we are doing it with `python-kubernetes`.

**Comment by evrardjp** [comment]
@kkaempf This will need prioritization.

**Comment by kkaempf** [comment]
> @kkaempf This will need prioritization.

I'm aware of this. Our current focus in CaaSP v5.

The SUSE Manager product manager has invited for a call on this topic for the 19th. Then we should have sufficient information to ask @qnetter for the priority.
