### ISSUE TITLE
Unable to bootstrap master node 

### ISSUE THREAD

**Issue by ajinkyaingole30** [SUSE/skuba#1124]
![Screenshot (273)](https://user-images.githubusercontent.com/38777540/82981236-24c10200-a009-11ea-86b1-b937d9791b72.png)

No provider of 'patterns-caasp-Node-1.18' found.

ip-10-0-0-120:~ # uname -a
Linux ip-10-0-0-120 4.12.14-197.40-default #1 SMP Fri Apr 17 12:23:07 UTC 2020 (b27cbb3) x86_64 x86_64 x86_64 GNU/Linux
ip-10-0-0-120:~ # cat /etc/os-release
NAME="SLES"
VERSION="15-SP1"
VERSION_ID="15.1"
PRETTY_NAME="SUSE Linux Enterprise Server 15 SP1"
ID="sles"
ID_LIKE="suse"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:15:sp1"
ip-10-0-0-120:~ #

**Comment by evrardjp** [comment]
Hello!

Our latest development builds are not ready for use yet! :)

If you want to use production ready, you could either build skuba with `make release` (which will change the code paths to registries, and use different patterns) or install our production rpms.

Please note that we currently rely on patterns, which are part of our CaaSP product repositories :)
Did you configure those repositories on your hosts? What does a `zypper lr` show?

**Comment by ajinkyaingole30** [comment]
![Screenshot (275)](https://user-images.githubusercontent.com/38777540/83031789-a4bf8a00-a052-11ea-8de3-3089de38b2cc.png)
o/p of zypper lr

**Comment by evrardjp** [comment]
sadly those aren't the good repos for our CaaSP product.
Kubic is another project. So is google-k8s :) 
I encourage you to try _only one_ at a time.

Kubic was designed with microOS in mind, not SLE. For SLE based k8s deployments, I encourage you to try our CaaSP product. You can follow it's documentation here: https://documentation.suse.com/suse-caasp/4.1/ . Sorry for the inconvenience.

**Comment by c3y1huang** [comment]
@ajinkyaingole30 development builds are not available to public. Please use a released branch and build with `make release`.

Closing.
