### ISSUE TITLE
kubeadm will go to beta3 in the future, we should handle it

### ISSUE THREAD

**Issue by evrardjp** [SUSE/skuba#1333]
See also https://github.com/SUSE/skuba/blob/c4c31d90cf3865c933ef763a85025bf9f23b15e7/internal/pkg/skuba/kubeadm/configmap.go#L70-L75 , and Rafa's talk on kubecon Europe 2020.

**Comment by evrardjp** [comment]
I am not working on this anymore. This issue has been stale for a while. Does it make sense to close the issue?

**Comment by manuelbuil** [comment]
> I am not working on this anymore. This issue has been stale for a while. Does it make sense to close the issue?

Yes! 
clean-up day? ;)

**Comment by evrardjp** [comment]
Indeed :)
