### ISSUE TITLE
Implement check that verifies add-ons updates

### ISSUE THREAD

**Issue by chentex** [SUSE/skuba#1418]
By design the add-on and the manifest version should be bumped together, I think this can be done with a check to avoid mistakes, like @evrardjp said.

_Originally posted by @chentex in https://github.com/SUSE/skuba/pull/1018#issuecomment-721007158_

Make sure to check that each time an add-on version is updated the manifest is also updated.

**Comment by evrardjp** [comment]
Correct, the manifests version needs a bump on addon version bump to be taken into consideration.
This can be implemented in unittest or elsewhere.
