### ISSUE TITLE
Document cluster's kubeconfig location and name

### ISSUE THREAD

**Issue by pablochacin** [SUSE/skuba#164]
In the documentation in [`README.md`](https://github.com/SUSE/caaspctl/blob/master/README.md) there's no mention where the cluster's `kubeconfig` is located or how to retrieve it. Presently, It happens to be in the cluster's directory under the name `admin.conf`.

**Comment by jodavis-suse** [comment]
Tweak to README.md ready for review.

**Comment by jodavis-suse** [comment]
PR https://github.com/SUSE/skuba/pull/938 merged, ready to stage
