### ISSUE TITLE
Unable to change registry for air gap solution

### ISSUE THREAD

**Issue by cseader** [SUSE/skuba#349]
When running a node boostrap for the first time when behind a DMZ your results are a kubeadm-init.conf file that is populated with registry.suse.com for all of the containers in the cluster. When you modify this file and change all traces of registry.suse.com to internal.registry.local and then rerun the node bootstrap its then overwritten and changed back to registry.suse.com. If I add a hosts entry to registry.suse.com, but the IP is my internal.registry.local, and rerun the node boostrap I get of course an invalid certificate error. 
How can I change the default registry used for skuba so I can have an air gap deployment? Can I change it somewhere in the code? Is there a config file that needs updated?

**Comment by chentex** [comment]
This was fixed with https://github.com/SUSE/skuba/pull/425
