### ISSUE TITLE
skuba CI module tests breaks if the order changes

### ISSUE THREAD

**Issue by bergmannf** [SUSE/skuba#483]
After running `go mod vendor` the `ci` will verify that the modules in use have not changed.

It does this by running:

```groovy
stage('Checking status of git tree') { steps {
            sh(script: 'test -z $(git status --porcelain go.mod go.sum vendor/) || { echo "there are uncommitted changes. This should never happen"; exit 1; }', label: 'git tree status')
} }
```

The `test -z` command verifies `vendor/` - however the file `vendor/modules.txt` sometimes only changes the *order* of dependencies, which will break this check even though the overall module situation has not changed:

- https://github.com/SUSE/skuba/pull/429/commits/bbf13b52763dce655b613c45f65d0032400feebd
- https://github.com/SUSE/skuba/pull/477/commits/17f9f1bb7854fdfa8f3d488d082126b733c1d58c

**Comment by chentex** [comment]
We are no longer using the vendor folder so this issue is no longer valid.
