### ISSUE TITLE
`zypper` call should include `-t pattern` when installing patterns.

### ISSUE THREAD

**Issue by dannysauer** [SUSE/skuba#487]
Doesn't `zypper` need a `-t pattern` indicating to install a pattern v/s a plain package here?

_Originally posted by @dannysauer in https://github.com/SUSE/skuba/pull/485_

**Comment by kkaempf** [comment]
> Doesn't `zypper` need a `-t pattern` indicating to install a pattern v/s a plain package here?

Strictly speaking, no.

A pattern is just an empty RPM package with specific `provides` and `requires`. Using `-t pattern` in zypper only makes pattern handling explicit and allows for a minimal simpler name.

`zypper in patterns-caasp-Node` and `zypper in -t pattern SUSE-CaaSP-Node` is technically equivalent.

**Comment by dannysauer** [comment]
The result is equivalent, sure. But the circumvention of the pattern abstraction is not. Directly installing the package is, IMO, no different than calling private methods from an imported class or some other similar bad practice.

**Comment by chentex** [comment]
Since on v4.5 we moved out of patterns I will close this.
