### ISSUE TITLE
--network-plugin=cni not in /var/lib/kubelet/kubeadm-flags.env

### ISSUE THREAD

**Issue by Hui-Zhi** [SUSE/skuba#727]
Following "[Deployment on Bare Metal](https://susedoc.github.io/doc-caasp/master/caasp-deployment/single-html/#deployment_bare_metal)", after configured 1 master and 2 nodes, found that ```cilium``` unable to start by checking the pods, the root cause is ```--network-plugin=cni``` is not in ```/var/lib/kubelet/kubeadm-flags.env```.

Before add ```--nework-plugin=cni``` to kubelet manually:
```shell
hui-zhi@linux-y6no:~/caasp> kubectl get pods --all-namespaces
NAMESPACE     NAME                               READY   STATUS     RESTARTS   AGE
kube-system   cilium-29vt8                       0/1     Init:0/3   0          3m55s
kube-system   cilium-4ksfd                       0/1     Init:0/3   0          3m58s
kube-system   cilium-4mkqp                       0/1     Init:0/3   0          3m52s
kube-system   cilium-operator-7d6ddddbf5-9vp7q   0/1     Pending    0          3m59s
kube-system   coredns-69c4947958-l7jpw           0/1     Pending    0          26h
kube-system   coredns-69c4947958-qp7l2           0/1     Pending    0          26h
kube-system   etcd-master0                       1/1     Running    0          26h
kube-system   kube-apiserver-master0             1/1     Running    0          26h
kube-system   kube-controller-manager-master0    1/1     Running    0          26h
kube-system   kube-proxy-nzcdk                   1/1     Running    0          21h
kube-system   kube-proxy-xgc2f                   1/1     Running    0          26h
kube-system   kube-proxy-zk4rq                   1/1     Running    0          21h
kube-system   kube-scheduler-master0             1/1     Running    0          26h
kube-system   oidc-dex-55fc689dc-4d4sj           0/1     Pending    0          26h
kube-system   oidc-gangway-7b7fbbdbdf-5wf7c      0/1     Pending    0          26h
```
After:
```
hui-zhi@linux-y6no:~/caasp> kubectl get pods -n kube-system
NAME                               READY   STATUS    RESTARTS   AGE
cilium-29vt8                       1/1     Running   1          141m
cilium-4ksfd                       1/1     Running   0          141m
cilium-4mkqp                       1/1     Running   0          141m
cilium-operator-7d6ddddbf5-9vp7q   1/1     Running   0          141m
coredns-69c4947958-l7jpw           1/1     Running   0          28h
coredns-69c4947958-qp7l2           1/1     Running   0          28h
etcd-master0                       1/1     Running   0          28h
kube-apiserver-master0             1/1     Running   0          28h
kube-controller-manager-master0    1/1     Running   1          28h
kube-proxy-nzcdk                   1/1     Running   0          23h
kube-proxy-xgc2f                   1/1     Running   0          28h
kube-proxy-zk4rq                   1/1     Running   0          23h
kube-scheduler-master0             1/1     Running   1          28h
kured-7njcj                        1/1     Running   0          132m
kured-8452v                        1/1     Running   0          132m
kured-vfk5f                        1/1     Running   0          132m
oidc-dex-55fc689dc-4d4sj           1/1     Running   1          28h
oidc-gangway-7b7fbbdbdf-5wf7c      1/1     Running   0          28h
```

**Comment by ereslibre** [comment]
Do you know why this is necessary on bare metal but not on virtualized environments? This flag only applies when the dockershim is used, which we are not using, since we are using the crio socket directly.

If the dockershim is used, `kubeadm` will add this flag automatically: https://github.com/kubernetes/kubernetes/blob/1c63eb1611116db1da720f83623144ef08770ada/cmd/kubeadm/app/phases/kubelet/flags.go#L84, but it's not the case.

**Comment by Hui-Zhi** [comment]
> Do you know why this is necessary on bare metal but not on virtualized environments? This flag only applies when the dockershim is used, which we are not using, since we are using the crio socket directly.
> 
> If the dockershim is used, `kubeadm` will add this flag automatically: https://github.com/kubernetes/kubernetes/blob/1c63eb1611116db1da720f83623144ef08770ada/cmd/kubeadm/app/phases/kubelet/flags.go#L84, but it's not the case (we are not using it).

1. Is this because we rely on virtualization environment network itself by default?
2. How can we run ```oidc```, ```cilium``` and ```coredns``` without ```--nework-plugin=cni```?

**Comment by pablochacin** [comment]
> Do you know why this is necessary on bare metal but not on virtualized environments?

I deployed a cluster using the baremeal instructions and didn't face this issue.

> Is this because we rely on virtualization environment network itself by default?

I used KVM virtual machines instead of physical nodes, but I don't think this make any difference, does it? 

I mean, beyond using dhcp address assignment for nodes provided by libvirt. Am I missing something here?

**Comment by ereslibre** [comment]
@Hui-Zhi cri-o is taking care of that, I think you are facing a different issue. Worth investigating, but I don't think it's related to that flag.

**Comment by Hui-Zhi** [comment]
@pablochacin I only have 1 workstation and 3 VMs on it, all CaaSP master and nodes are on the 3 VMs.
@ereslibre I agreed, but it's weird it works after I added ```network-plugin=cni```, because I am using ```cri-o``` and it should take care of it. I will look into this issue, please keep this issue open at present.

**Comment by ereslibre** [comment]
Thanks @Hui-Zhi, please share any findings.

**Comment by Hui-Zhi** [comment]
Have tried to reproduce this with below steps, but it can not be reproduced, I think it might caused by my environment is "short of" hardware, it takes at least 10 minutes to get a node ready after ```skuba join xxx``` success. 

Testing I did:
1. Remove ```network-plugin=cni```, and reboot all nodes (include master). It turns out it still works without this argument. ```kubectl logs``` didn't give any hint about why it doesn't work before.

2. Create a new environment (1 node and 1 master) and enable docker before install CaaSP (simulate what my environment looks like).  It works without ```network-plugin=cni```.

3. Create a new environment (1 node and 1 master) and install CaaSP directly. It works without ```network-plugin=cni```.

I think we can close this, I will open another issue if found it's not just caused by the network building slow.
