### ISSUE TITLE
command-line completion for skuba command

### ISSUE THREAD

**Issue by dannysauer** [SUSE/skuba#792]
### Summary

As a skuba user, I'd like the ability to press the completion key in my shell, and have command line arguments to skuba be expanded.  This would reduce the likelihood of misspelling long arguments, reduce the time it takes to check the "help" output, and generally provide a more polished feel.  The upstream commands (kubectl/kubeadm) have an option which emits completion code for shell inclusion, so this would bring us more feature parity as well.

As a developer, I'd like to know more about how skuba parses command line arguments.  Developing shell completion code will give me practical experience learning about argument parsing in skuba.

As a Bash user, I'd like to increase my depth of knowledge about how programmable completion works in Bash.

### Acceptance Criteria

- [x] stand-alone programmable completion for Bash is written in a way that allows relatively simple expansion as new CLI arguments are added
- [x] ticket to implement automated generation of Bash completion code directly within skuba is created
- [x] assessment of feasibility for also generating zsh completion code is documented in this ticket
- [ ] completion ideas (guess nodename based on target IP, predict hostnames from known hosts file or /etc/hosts, etc) which might take "longer than reasonable to implement" are documented in this ticket

**Comment by kravciak** [comment]
You might be able to reuse some code from PR https://github.com/SUSE/skuba/pull/95

**Comment by dannysauer** [comment]
Neat; there's a generator built in. Well, that counts as learning about the arg parser. :D

https://github.com/spf13/cobra/blob/master/bash_completions.go#L527

(clearly I should've searched closed issues too; thanks @kravciak)

**Comment by dannysauer** [comment]
Marking off the checkboxes while I clean stuff up this morning:
 * This _is_ the ticket for developing the code now
 * Since it's built-in to Cobra, addition of new options is automatic
 * Feasibility of zsh code: 100% doable at the same time. :D

**Comment by tdaines42** [comment]
I think the extra stuff should be it's own issue if it's something we want to do. Is there anything that needs to be done by me to get this done?

**Comment by dannysauer** [comment]
I think we can probably leave enhancements for later, after people have used this and given feedback.
