### ISSUE TITLE
`skuba cluster upgrade plan` shows confusing version info after the 1st control plane node updated

### ISSUE THREAD

**Issue by innobead** [SUSE/skuba#866]
As per https://github.com/SUSE/skuba/pull/853#issuecomment-560185221, after upgrading the first control plane node, executing `skuba cluster upgrade plan` again shows below confusing info even the following nodes not upgraded yet.

** This is an UNTAGGED version and NOT intended for production usage. **
```
Current Kubernetes cluster version: 1.16.2
Latest Kubernetes version: 1.16.2

Congratulations! You are already at the latest version available
```

The worker is not upgraded yet but the cluster upgrade plan doesn't show me that. It can be confusing during an upgrade.

cc @maximenoel8 @cclhsu @jenting @c3y1huang

**Comment by c3y1huang** [comment]
@innobead I think this one is duplicated and @ereslibre already have PR WIP: SUSE/skuba#911 .

**Comment by ereslibre** [comment]
Yes, thank you @c3y1huang, this is a duplicate and will be addressed by https://github.com/SUSE/skuba/pull/911.

**Comment by innobead** [comment]
Thanks for the update ;)
