### ISSUE TITLE
Trouble adding Nodes to the cluster.

### ISSUE THREAD

**Issue by j-n-s-k-n-r** [SUSE/skuba#884]
Cheers,

i'm having trouble using Skuba to add servers to a cluster.
I'm trying to use the command
`„skuba node bootstrap --user jonas --sudo --target server2.XYZ.de master1“`
to add the first master node to the cluster. The cluster was created some minutes ago

However, the process is aborted with the error
`„bootstrapping node: failed to apply state kubernetes.install-node-pattern: Process exited with status 8“ `. 
Skuba had no problem with the SSH Connection.
I followed the official instructions of the SUSE [Documenation](https://documentation.suse.com/suse-caasp/4.0/single-html/caasp-deployment/#_deployment_on_existing_sles_installation) when creating and setting up the cluster and the master node. 
I cannot find the error code `"Status 8"` in the documentation. Do you have any idea what doesn't work or what status 8 means?
Information concerning the systems used is attached.

**OS:** Sles15 SP1
**uname -a:** Linux server2 4.12.14-195-default x86_64 GNU/Linux

Many thanks in advance.

**Comment by Suse-KevinKlinger** [comment]
Hey folks,

I am facing the same issue today.
OS: SLES 15 SP1
Skuba-version: v1.0.2
Kubectl-version: 1.15.2

Is there any progress on this?

**Comment by jenting** [comment]
@j-n-s-k-n-r @Suse-KevinKlinger Could you please run `skuba version` to make sure you're using the production images, thx.

**Comment by j-n-s-k-n-r** [comment]
@jenting 

Thanks for your reply.

But actually this can be closed, we have now switched to another solution.

But thank you for your time.
