### ISSUE TITLE
Bring tf output in sync for all platforms

### ISSUE THREAD

**Issue by Itxaka** [SUSE/skuba#914]
commit 084b421 introduced a change in
the output for the libvirt deployments which now included the node
names.

output moved from this:

```
hostnames_masters = [
    clee-master-0,
    clee-master-1,
    clee-master-2
]
hostnames_workers = [
    clee-worker-0,
    clee-worker-1,
    clee-worker-2
]
ip_load_balancer = 10.17.1.0
ip_masters = [
    10.17.2.0,
    10.17.2.1,
    10.17.2.2
]
ip_workers = [
    10.17.3.0,
    10.17.3.1,
    10.17.3.2
]
```

to this:

```
{
    "ip_load_balancer": {
        "sensitive": false,
        "type": "map",
        "value": {
            "itxaka-lb": "10.17.1.0"
        }
    },
    "ip_masters": {
        "sensitive": false,
        "type": "map",
        "value": {
            "itxaka-master-0": "10.17.2.0",
            "itxaka-master-1": "10.17.2.1",
            "itxaka-master-2": "10.17.2.2"
        }
    },
    "ip_workers": {
        "sensitive": false,
        "type": "map",
        "value": {
            "itxaka-worker-0": "10.17.3.0",
            "itxaka-worker-1": "10.17.3.1",
            "itxaka-worker-2": "10.17.3.2"
        }
    }
}
```

That change also broke deploying on libvirt so https://github.com/SUSE/skuba/pull/912 was created to fix it.

It was agreed that a follow up patch by @suseclee would be done to bring the other platforms in sync with this change and have all save the same output.

**Comment by Itxaka** [comment]
cc @pablochacin @suseclee @evrardjp

**Comment by suseclee** [comment]
Outputs:

From 
```
hostnames_masters = []
ip_internal_load_balancer = 172.28.0.5
ip_load_balancer = 10.86.4.225
ip_masters = [
    10.86.2.67
]
ip_workers = [
    10.86.3.104,
    10.86.0.186,
    10.86.4.132
]
```
TO:
```
ip_load_balancer = {
  clee-lb = 10.86.0.181
}
ip_masters = [
    {
        caasp-master-clee-0 = 10.86.0.229
    }
]
ip_workers = [
    {
        caasp-worker-clee-0 = 10.86.3.63,
        caasp-worker-clee-1 = 10.86.3.104,
        caasp-worker-clee-2 = 10.86.4.11
    }
]
```

I removed ip_internal_load_balancer. Let me know if this is needed or is there anything to be added. 
And the output format. This should be same format as current libvirt output.

**Comment by Itxaka** [comment]
@suseclee I wiped out this yesterday but didnt push it until today, let me know if this works for you: https://github.com/SUSE/skuba/pull/916

**Comment by suseclee** [comment]
I have worked on this since this was assigned to me. But ltxaka has already pushed PR. I removed myself from this issue.
