### ISSUE TITLE
Disable `firewalld`

### ISSUE THREAD

**Issue by ereslibre** [SUSE/skuba#919]
Skuba should disable `firewalld` when bootstrapping/joining a node. Currently, this is done by `cloud-init` in certain deployments with `terraform`.

Being this a deployment trait, `skuba` should make sure that this service is disabled, so it doesn't cause any unexpected issues.

**Comment by evrardjp** [comment]
Not sure what's the intent of this issue, as it lacks explanations on _why_ we want to do this.

As firewalld can handle bridges and NAT, I don't think disabling the service is the right idea.
Instead we should probably change rules to allow everything in runtime, and restart the firewalld service when we are done, to re-use the rules that are stored in the permanent configuration.

https://firewalld.org/documentation/configuration/runtime-versus-permanent.html

**Comment by ereslibre** [comment]
We are disabling `firewalld` with terraform for `libvirt` and `vmware`, and the JeOS image used for `openstack` don't have `firewalld` at all.

This imposes a hidden dependency on `terraform`, assuming from `skuba` side that `terraform` will disable this service. However, customers can use whatever they prefer to create the infrastructure, they can rely on `terraform` if they don't have anything else to create the infra.

In this case, `skuba` should make sure that `firewalld` is disabled so we get rid of this hidden dependency.

**Comment by evrardjp** [comment]
But what's the problem that was the reason of disabling firewalld with libvirt and vmware in the first place?

I am worried about disabling firewalld for two reasons:
- either we then have two different code paths for customers and our CI for this, which isn't great
- or we disable firewalld in a customer environment, which doesn't sound so secure.

I understand that the hidden dependency shouldn't be there. But I also am not sure whether disabling the firewall altogether is the right way.

**Comment by ereslibre** [comment]
> But what's the problem that was the reason of disabling firewalld with libvirt and vmware in the first place?

It is preventing the apiserver from being reachable. Also, it makes all platforms even, because JeOS (openstack image) does not have `firewalld`.

> I am worried about disabling firewalld for two reasons:

This is the case already, `firewalld` either is not installed at all (JeOS), or disabled (libvirt, vmware).

This issue just proposes to remove this logic from terraform and implement it on `skuba`, so if a user deploys the infrastructure with their own tooling, `skuba` will take care of making sure that everything is as expected.

I understand your concern, but enabling firewalld and making sure that all rules exist and are as expected would be a different task and we should treat it as a new item in our backlog, since it's a new security feature.

**Comment by evrardjp** [comment]
I would expect that's what we should do instead. Or leave it to the user altogether, and only implement a pre-flight check if firewalld would filter the api server, and error out if it's the case -- a properly configured firewall or a disabled firewalld would not pose any problem, and it sounds far better than disabling firewalld (it's also better in case the user doesn't use firewalld).

**Comment by ereslibre** [comment]
> I would expect that's what we should do instead.

I think enabling firewalld (and that its rules are fine, and that they don't clash with other Kubernetes' iptables rules) is a different task.

This issue is just about moving the action of disabling firewalld from terraform to skuba. What you propose requires more QA, checking if we are missing something in the rules, check if they create any kind of issue on the rest of Kubernetes components that use iptables...

**Comment by evrardjp** [comment]
Indeed what I am proposing is a ton more work... :/ 
But that's what I think is best because of the user impact.

I don't imply that's what we'll implement. At least I have said my word. :)

**Comment by ereslibre** [comment]
Nothing prevents us from going after that. The only thing I'm saying is that we have been disabling firewalld; let's do that correctly (without depending on how we create the infra), and let's add a firewalld task on our backlog.
