### ISSUE TITLE
Check that the kernel has the required modules for regular operation

### ISSUE THREAD

**Issue by ereslibre** [SUSE/skuba#920]
`skuba` needs to check that the running kernel suffices to provide all the features the Kubernetes cluster will need.

At this time we are reinstalling `kernel-default` with terraform, but this imposes a hidden dependency on `terraform`, rendering invalid any deployment without it, since `skuba` does not perform any preflight checks.

**Comment by evrardjp** [comment]
Could you clarify what is need and why are some modules needed, please?

**Comment by ereslibre** [comment]
This will need some input from @mrostecki.

**Comment by mrostecki** [comment]
For sure `br_netfilter` and `vxlan`. I need to check whether more are needed.

**Comment by mrostecki** [comment]
Apart from modules, I would also check sysctls, whether they have value `1`:

- `/proc/sys/net/ipv4/ip_forward`
- `/proc/sys/net/ipv4/conf/all/forwarding`

**Comment by mrostecki** [comment]
To sum it up, I think that checking for:

- modules
  * `br_netfilter`
  * `vxlan`
- sysctls
  * `/proc/sys/net/ipv4/ip_forward`
  * `/proc/sys/net/ipv4/conf/all/forwarding`

Should be enough to differentiate between having `kernel-default` instead of `kernel-default-base`.
