### ISSUE TITLE
Not able to configure the hostIP

### ISSUE THREAD

**Issue by manuelbuil** [SUSE/skuba#953]
hostIP is an important config parameter in crio.conf because it sets the IP that the pods in hostNetwork mode will use. Right now that parameter is not set:

```
# Host IP considered as the primary IP to use by CRI-O for things such as host network IP.
host_ip = ""
```

As a consequence, a default value gets chosen. That value is the IP of the interface used as gateway. A user might want to use another interface (for example when deploying CaaSP in public cloud [1]) and thus we should have a way to configure this.

[1] - https://github.com/kubernetes/kubeadm/issues/203

**Comment by aojea** [comment]
Cloud providers use only one interface, the issue you mention is related to the use of "floating IPs" on the cloud providers, that basically means that they use IPs that are not present in the instance.
To solve that kubelet has a different logic to configure the "node" ip addresses, if using a cloud-controller,  allows the cloud-controller to overwrite the node IPs.
However, coming back to your question, I really don't know how CRI-O uses that info, but host_ip should be the same address reported by kubelet as node_ip IMHO ... definitively we should try to get more clear uses cases about this problem to understand it better

**Comment by manuelbuil** [comment]
I don't think we are talking about the same problem. Unfortunately, that thread has a lot of different topics popping up. I am referring to the one that "mongrelion" reports, which if I understand correctly, is exactly the one I am seeing. Imagine you have several servers with NIC1 and NIC2. NIC1 connects you to the world and thus is your default gateway. NIC2 connects you to your small private network that you want to use for K8s. You deploy K8s and when executing `kubectl get nodes -o wide` you see the ip of NIC2 for each node. Great! Now you deploy pods in hostNetwork mode and when checking their IP, you suddenly realize that they are using the IP of NIC1. That is bad! Just to give you an example why this is bad: cilium-agent is running in hostNetwork mode and uses the MTU of the interface to set the MTU of all Cilium elements in the datapath (cilium_vxlan, cilium_host, lxc interfaces....). If MTU of NIC1 is 1500 and MTU of NIC2 is 9000, Cilium will use 1500 bytes even though we wanted 9000.

Yes, you are correct, we can also define the hostIP as a kubelet parameter, however, we are not doing that either.

I think this is an issue we should solve. After hackweek I'll start socializing this problem and if I can gather enough support, then we can move into solutions-mode :)

**Comment by aojea** [comment]
>  I am referring to the one that "mongrelion" reports

hey, I was missing all the context, never heard about that "mongrelion" thing :sweat_smile: 

> I don't think we are talking about the same problem.
yeah, disregard my answer, multiple nics are something totally different to what I answer :sweat_smile: 

kubelet and host_IP is a long standing topic that I'm working for some time with the dual-stack thing ;)

**Comment by manuelbuil** [comment]
> > I am referring to the one that "mongrelion" reports
> 
> hey, I was missing all the context, never heard about that "mongrelion" thing sweat_smile
> 
> > I don't think we are talking about the same problem.
> 
> yeah, disregard my answer, multiple nics are something totally different to what I answer sweat_smile
> 
> kubelet and host_IP is a long-standing topic in SIG-network that I'm working for some time with the dual-stack thing ;) , I can give you some insights on where is blocked upstream

Awesome! Let's discuss after hackweek. This is something that SES guys will require as they use 100Gb NICs for storage replication and slower and cheaper NICs for the rest of traffic. We could also trigger a wider investigation about how to achieve control plane vs data plane separation in K8s because this issue is part of it, right? I am sure you can help me understand the upstream situation of that topic and then we could decide what alternative to use for Skuba :)

**Comment by aojea** [comment]
the limit on Linux networking is not the NIC is the CPU, 1current HW is not able to handle 10 Gbps maximum packet rate 14.88 Mpps (million packets per sec) uni-directional on 10Gbit/s with the smallest frame size, with 100 Gbps it will be more difficult. GSO/GSO offloading alleviates the problem, but only for TCP and limited to bulking/aggregation on a per flow basic, shorter flows are still a problem.

http://netoptimizer.blogspot.com/2014/05/the-calculations-10gbits-wirespeed.html?q=cycles

However, an scenario with only 64 bytes packets is a corner, but the other way around ,with traffic only with large packets is unrealistic too. 

The other bottlenecks I see are the disks speed and the PCIe, I'm not very familiar with this area, but my google foo says that the PCIe v5.0 has 31,5 Gbit/s (3938,4 MB/s) per slots 🤔 ... what kind of disks are we talking about?

**Comment by manuelbuil** [comment]
After some hours investigating this, I think I understand what is going on. This is how the hostIP gets set for each node:

#1 - It checks if nodeIP is set, either at crio.conf or, preferably, as a kubelet flag "--node-ip". If nothing is set, it moves to #2
#2 - Checks the parameter hostnameOverride in case there is an IP. If not, it moves to #3 
#3 - Looks up the name of the server using DNS and fetches the IP from there. If not, it moves to #4 
#4 - Uses the ip from the interface that acts as default gateway

In our case, we are normally getting the hostIP through step #3. Skuba does not configure node-ip or hostIP, nor hostnameOverride with an IP. However, the master and worker name must be resolvable by DNS (e.g. by being in /etc/hosts), if not, it moves to #4 and this is where things might get weird.

What caused my confusion was that when using `skuba bootstrap` or `skuba join`, an IP (or a resolvable hostname) must be specified to reach the node. That IP has nothing to do with the hostIP, which gets set by the described algorithm.  E.g. `skuba node join --role worker --user sles --sudo --target $IP_A worker1`, if worker1 is registered with a different IP in the DNS server, the internal IP will be that one and not $IP_A, even though $IP_A was used to provision the node. To me this is a bit confusing and it might be nice to clarify it in the documentation (but I'd prefer others to comment before doing so, perhaps it is only confusing to me)

BTW, I could not reproduce again the scenario where `kubectl get nodes -o wide` shows an INTERNAL-IP different from selected hostIP. If somebody else is seeing this, please contact me!

Anyway, I'd say this issue is not valid anymore because by having a correct DNS configuration, this issue gets solved, i.e. we don't need to configure hostIP in crio.conf or --node-ip in kubelet.
