### ISSUE TITLE
failure disarming kubelet happening very often when `skuba node remove`

### ISSUE THREAD

**Issue by manuelbuil** [SUSE/skuba#978]
When executing `skuba node remove`, I very often encounter the error:

`[remove-node] failed disarming kubelet: failed waiting for job caasp-kubelet-disarm-e26cca0cad7cbe78840fe7a3f252ad236f15983d; node could be down, continuing with node removal...`

The removal finalizes correctly, as I cannot see the node anymore when querying kube-api. However, the node still has kubelet, crio, cilium interfaces... etc running.

**Comment by ereslibre** [comment]
Thank you @manuelbuil, it's tracked here: https://github.com/SUSE/avant-garde/issues/1455
